---
title: "Stomach cancer paper Figure Sup 1"
author: "Vi Dang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    css: font.css
---

```{r setup, include = FALSE}
# Set global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)
```

```{r }
# Load libraries
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(patchwork)
library(RColorBrewer)
```
```{r }
# Specify the path
main_path <- '/group/poetsch_projects/poetsch_sc/Stomach_paper_repository'
rds_path  <- file.path(main_path,'RDS')
txt_files <- file.path(main_path,'txt_files')
plot_path <- file.path(main_path,"Figures")
figures_data <- file.path(main_path,"Figures_data")
dir.create(figures_data)
```
# QC results: Number of cells, number of UMIs/cell, number of feature/cell
```{r }
#Load input file
seurat_integrated <- readRDS(file.path(rds_path, "three_patient_integrated_cca_ref.rds"))

#change sample names
meta <- seurat_integrated@meta.data
meta <- meta %>%
  mutate(Sample = case_when(
    grepl("-no", orig.ident) ~ sub("-no", " Untreated", orig.ident),
    grepl("-vitro", orig.ident) ~ sub("-vitro", " Ex vivo", orig.ident),
    grepl("-vivo", orig.ident) ~ sub("-vivo", " In vivo", orig.ident),
    TRUE ~ orig.ident
  ))
seurat_integrated@meta.data <- meta
```

```{r fig.width = 14, fig.height = 15}
#set color
color_palette <- c(brewer.pal(12, "Set3")[1:8],  brewer.pal(8, "Set2")[4])
#Plot number of cells
meta <- seurat_integrated@meta.data 
sample_order = c("OO77 Untreated"  , "OO77 Ex vivo" ,  "OO77 In vivo" ,
                    "OO99 Untreated"  ,    "OO99 Ex vivo" , "OO99 In vivo" ,
                    "OO100 Untreated" , "OO100 Ex vivo" , "OO100 In vivo" )

meta$Sample <- factor(meta$Sample, levels = sample_order)
meta_sum <- meta %>% group_by(Sample) %>% summarize(n_cells= n())
p1 = meta_sum %>% ggplot(aes(x = Sample , y= n_cells, fill = Sample )) +
             geom_bar(stat = "identity", width = 0.6)+
             geom_text(aes(label = n_cells), vjust = -0.5, size = 10) +
             ylim(0,9000)+
             scale_fill_manual(values = color_palette  )+
             ylab("Number of cell") +
             xlab("Sample")+ 
             theme_classic() +
             theme(legend.position= "None", 
               legend.title = element_text(size = 28, color = "black"),
                legend.text = element_text(size = 28, color = "black"),
                axis.text.x = element_blank(),
                axis.title.x.bottom = element_blank(),
                plot.title = element_text(size = 28, color = "black"),
                axis.text.y.left = element_text(size = 28, color = "black"),
                axis.title.y.left = element_text(size = 28, color = "black"))
             # + ggtitle("Number of cell")
      

data = p1$data
write.table(data, file.path(figures_data, "Figure_Sup_1_number_of_cell_per_sample.txt"),sep = "\t", quote = F) 

#Boxplot
options(scipen = 999)  
p2 = meta %>% ggplot(aes(x = Sample, y =  nCount_RNA,group = Sample,  fill =  Sample))+
         geom_boxplot()+
         scale_fill_manual(values =color_palette )+
         ylim(0,130000)+
          xlab("Sample")+ 
          ylab("Number of UMI / cell") +
          theme_classic() +
             theme(legend.position= "None", 
                axis.text.x = element_blank(),
                axis.title.x.bottom = element_blank(),
                plot.title = element_text(size = 28),
                   axis.text.y.left = element_text(size = 28, color = "black"),
                   axis.title.y.left = element_text(size = 28, color = "black")) 
           # + ggtitle("Number of UMI/cell")


data = p2$data
write.table(data, file.path(figures_data, "Figure_Sup_1_nUMI_per_cell_per_sample.txt"),sep = "\t", quote = F) 

p3 =  meta %>% ggplot(aes(x = Sample, y =  nFeature_RNA,group = Sample,  fill =  Sample))+
         geom_boxplot()+
         scale_fill_manual(values = color_palette  )+
         ylim(0,15000)+
          xlab("Sample")+ 
          ylab("Number of gene/cell") +
          theme(legend.position= "None")+
          theme_classic() +
             theme(legend.position= "None", 
                axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 28, color = "black"),
                axis.title.x.bottom = element_blank(),
                plot.title = element_text(size = 38, color = "black"),
                axis.text.y.left = element_text(size = 28, color = "black"),
                axis.title.y.left = element_text(size = 28, color = "black")) 
         # + ggtitle("Number of gene/ cell")

p1 + p2 + p3 + plot_layout(nrow = 3)
ggsave(file.path(plot_path,"Figure_Sup_1_nGene_per_cell_per_sample.pdf"), width = 14, height = 15)

data = p3$data
write.table(data, file.path(figures_data, "Figure_Sup_1_nGene_per_cell_per_sample.txt"),sep = "\t", quote = F) 
```

```{r }
#Calculate median
#median number of cell per sample
median(meta_sum$n_cells)
#median number of UMNI per cell
median(meta$nCount_RNA)
#median number of gene per cell
median(meta$nFeature_RNA)
```
# Different cell types markers
```{r }
#Normalize and scale data
DefaultAssay(seurat_integrated)<-'RNA'
options(future.globals.maxSize = 10 * 1024^3)
seurat_integrated <- SCTransform(seurat_integrated,  vst.flavor = "v1",
                                 #method = "glmGamPoi",
                                 verbose = FALSE)

seurat_integrated <- RunPCA(seurat_integrated, npcs = 30, verbose = F)
seurat_integrated <- RunUMAP(seurat_integrated, reduction = "pca", dims = 1:30, verbose = F)
```


```{r fig.width = 14, fig.height = 6}
# Markers
Markers = c("EPCAM","PECAM1", "FBN1", "CD3E",
            "CDH1","CD34", "COL3A1", "PIM2")

# Generate FeaturePlots
plots <- FeaturePlot(seurat_integrated, features = Markers, ncol = 4, raster = TRUE, pt.size = 1.25)

# Increase legend text size for each plot
plots <- lapply(plots, function(p) {
  p + theme(legend.text = element_text(size = 17))  # Adjust size as needed
})


combined_plot <- wrap_plots(plots, ncol = 4) 
combined_plot

plot_data_list <- lapply(plots, function(p) p$data)

# Optionally, name each list element with the marker name
names(plot_data_list) <- Markers

df = plot_data_list[[1]] 
for (marker in Markers[2:8]){
 df = df %>% cbind(plot_data_list[[marker]][marker]) 
}
                                              
colnames(df)[3] = "sample"     

```


```{r}
sessionInfo()
```

