---
title: "Stomach cancer paper Figure Sup 8A"
author: "Vi Dang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    css: font.css
---

```{r setup, include = FALSE}
# Set global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)
```

```{r }
library(tidyverse)
library(ggpubr)
library(vegan)
library(Seurat)
library(ggplot2)
library(RColorBrewer)
library(stats) 
```

```{r }
# Specify the path
main_path <- '/group/poetsch_projects/poetsch_sc/Stomach_paper_repository'
rds_path  <- file.path(main_path,'RDS')
txt_files <- file.path(main_path,'txt_files')
plot_path <- file.path(main_path,"Figures")
figures_data <- file.path(main_path,"Figures_data_2")
dir.create(figures_data)
```


# Genetic ITH
```{r }
#OO77
# Clone proportion in scRNA-seq
OO77_clone_pro = read.delim(file.path(txt_files, "OO77_Clone_proportion.txt"))
OO77_clone_pro  = OO77_clone_pro %>% mutate(sample = case_when(sample == "OO77-no" ~ "OO77_tumor",
                                                              sample == "OO77-vitro" ~ "OO77_ex",
                                                              sample == "OO77-vivo" ~ "OO77_in"))

OO77_clone_pro = OO77_clone_pro %>% pivot_wider(names_from = "sample", values_from = "proportion",  values_fill = list(proportion = 0))
colnames(OO77_clone_pro)[1] = "clusterID"

#OO99
# Clone proportion in scRNA-seq
OO99_clone_pro = read.delim(file.path(txt_files, "OO99_Clone_proportion.txt"))
OO99_clone_pro  = OO99_clone_pro %>% mutate(sample = case_when(sample == "OO99-no" ~ "OO99_tumor",
                                                              sample == "OO99-vitro" ~ "OO99_ex",
                                                              sample == "OO99-vivo" ~ "OO99_in"))
OO99_clone_pro = OO99_clone_pro %>% pivot_wider(names_from = "sample", values_from = "proportion",  values_fill = list(proportion = 0))
colnames(OO99_clone_pro)[1] = "clusterID"

#OO100
# Clone proportion in scRNA-seq
OO100_clone_pro = read.delim(file.path(txt_files, "OO100_Clone_proportion.txt"))
OO100_clone_pro  = OO100_clone_pro %>% mutate(sample = case_when(sample == "OO100-no" ~ "OO100_tumor",
                                                              sample == "OO100-vitro" ~ "OO100_ex",
                                                              sample == "OO100-vivo" ~ "OO100_in"))
OO100_clone_pro = OO100_clone_pro %>% pivot_wider(names_from = "sample", values_from = "proportion",  values_fill = list(proportion = 0))
colnames(OO100_clone_pro)[1] = "clusterID"

```

```{r }
#Weghted Shannon entropy

calculate_Entropy <- function(sample, patient, clone_proportion_df){
    df  <- clone_proportion_df %>%
          select(!!sym(sample), clusterID) %>%
          filter(!!sym(sample) > 0)
          colnames(df)[1] <- "proportion"

    df <- df %>% mutate(Entropy = proportion/100 * log(proportion/100)  )
    tumor_Entropy <- - sum(df$Entropy)
    result = data.frame(patient = patient, Treatment = str_split(sample,"_")[[1]][2], ITH = tumor_Entropy)
    result
}   

samples = c("OO77_tumor","OO77_ex", "OO77_in")
OO77_Entropy = purrr::map_dfr(samples, ~calculate_Entropy(.x, patient = "OO77", clone_proportion_df = OO77_clone_pro))

samples = c("OO99_tumor","OO99_ex", "OO99_in")
OO99_Entropy = purrr::map_dfr(samples, ~calculate_Entropy(.x, patient = "OO99", clone_proportion_df = OO99_clone_pro))

samples = c("OO100_tumor","OO100_ex", "OO100_in")
OO100_Entropy = purrr::map_dfr(samples, ~calculate_Entropy(.x, patient = "OO100", clone_proportion_df = OO100_clone_pro))

All = rbind(OO77_Entropy, OO99_Entropy, OO100_Entropy)

All$patient = factor(All$patient, levels = c("OO77", "OO99", "OO100"))
# Create a new column for labeling only tumor samples
#All$label <- ifelse(All$Treatment == "tumor", All$patient, NA)

#Untreated and In vivo
All_in <- All %>% filter(Treatment != "ex")
All_in$Treatment = factor(All_in$Treatment, levels = c("tumor","in"))

#t test
t_test <- t.test(ITH ~ Treatment, data = All_in, paired = TRUE, alternative = "greater")
p_value <-  t_test$p.value
```

```{r fig.width = 5, fig.height = 5}

colors = c("deepskyblue2","plum", "goldenrod3", "darkcyan","indianred1")

#Plot
ggplot(All_in, aes(x = Treatment, y = ITH , group = patient)) +
  geom_point(aes(colour = Treatment),  size = 4, alpha = 0.5, position = position_dodge(width = 0)) +
  geom_line(aes(group = patient, colour = patient), linewidth = 2, alpha = 0.5, position = position_dodge(width = 0)) +
  scale_y_continuous(limits = c(-0.5,2.7), breaks = c(0,1,2,3))+
  scale_x_discrete(labels = c("in"="In vivo","tumor" = "Untreated"))+
  scale_colour_manual(values = colors)+
  ylab("genetic ITH") +
  #geom_text(aes(label = label), vjust = -0.5, position = position_dodge(width = 0.5), size = 6) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 20, color = "black"),
        axis.title.y = element_text(size = 20, color = "black"),
        axis.text.y = element_text(size = 20, color = "black"),
         panel.spacing = unit(1, "lines"))  +
  # Add the p-value as annotation
  annotate("text", x = 1.5, y = 2.5, label = paste("p =", format.pval(p_value, digits = 3)), size = 8)

ggsave(file.path(path=plot_path,"Figure_Sup_8A_Genetic_ITH.pdf"),width= 6.5,height=6.5)


#Save Figure data
write.table( All, file.path(figures_data, "Figure_Sup_8A_Genetic_ITH.txt"), sep = "\t", quote = F)

```

# Transcriptomic ITH
```{r }
seurat <- readRDS(file.path(rds_path,"three_patient_integrated_cca_ref.rds"))
DefaultAssay(seurat) = "RNA"
options(future.globals.maxSize = 10 * 1024^3)  # 8 GB

seurat <- SCTransform(seurat , vst.flavor = "v1",
                                 #method = "glmGamPoi",
                                 verbose = FALSE)

seurat <- RunPCA(seurat, npcs = 30, verbose = F)
seurat <- RunUMAP(seurat, reduction = "pca", dims = 1:30, verbose = F)

#change the name of sample
meta <- seurat@meta.data
meta <- meta %>%
  mutate(sample = case_when(
    grepl("-no", orig.ident) ~ sub("-no", " Untreated", orig.ident),
    grepl("-vitro", orig.ident) ~ sub("-vitro", " Ex vivo", orig.ident),
    grepl("-vivo", orig.ident) ~ sub("-vivo", " In vivo", orig.ident),
    TRUE ~ orig.ident
  ))
seurat@meta.data <- meta

pca_embeddings <- Embeddings(seurat, reduction = "pca")[, 1:30]
pca_df <- data.frame(pca_embeddings, Sample = seurat@meta.data$sample)


sum_distance_per_sample <- function(pca_df) {
  # Ensure the Sample column exists
  if (!"Sample" %in% colnames(pca_df)) {
    stop("The data frame must contain a 'Sample' column.")
  }
  
  # Split data by sample
  samples <- unique(pca_df$Sample)
  norm_distances <- numeric(length(samples))
  names(norm_distances) <- samples
  
  for (sample in samples) {
    # Subset PCA data for the current sample
    sample_data <- pca_df[pca_df$Sample == sample, 1:30]
    
    # Compute pairwise Euclidean distances
    dists <- as.matrix(dist(sample_data, method = "euclidean"))
    
    # Sum all distances in the matrix (upper triangle to avoid double counting)
    total_distance <- sum(dists) / 2
    
    # Normalize by the number of cells in the sample
    num_cells <- nrow(sample_data)
    
    if (num_cells > 1) {
      norm_distances[sample] <- total_distance / (num_cells * (num_cells-1)* 1/2)
    } else {
      norm_distances[sample] <- 0  # If only one cell, distance is zero
    }
  }
  
  return(norm_distances)
}


norm_distances <-  sum_distance_per_sample(pca_df)
norm_distances_df <- as.data.frame (norm_distances)

norm_distances_df <- norm_distances_df %>% tibble::rownames_to_column("sample")
colnames(norm_distances_df )[2] = "ITH"

norm_distances_df <- norm_distances_df %>% 
  mutate(
    patient = sub(" .*", "", sample),   # Extract text before the first space
    treatment = sub(".*? ", "", sample) # Extract text after the first space
  )

All <- norm_distances_df
All$patient = factor(All$patient, levels = c("OO77", "OO99", "OO100"))
# Create a new column for labeling only tumor samples
All$label <- ifelse(All$treatment == "Untreated", All$patient, NA)

#Untreated and In vivo
All_in <- All %>% filter(treatment != "Ex vivo")
All_in$treatment = factor(All_in$treatment, levels = c("Untreated","In vivo"))

#t test
t_test <- t.test(ITH ~ treatment, data = All_in, paired = TRUE, alternative = "greater")
p_value <-  t_test$p.value
```

```{r fig.width = 5, fig.height = 5}
colors = c("deepskyblue2","plum", "goldenrod3", "darkcyan","indianred1")
#Plot
ggplot(All_in, aes(x = treatment, y = ITH , group = patient)) +
  geom_point(aes(colour = treatment), size = 4,alpha = 0.5 , position = position_dodge(width = 0)) +
  geom_line(aes(group = patient, colour = patient), linewidth = 2, alpha = 0.5, position = position_dodge(width = 0)) +
  scale_y_continuous(limits = c(-5,max(All_in$ITH + 50)), breaks = c(0, 50,100))+
  scale_colour_manual(values = colors)+
  ylab("Transcriptomic ITH") +
  #geom_text(aes(label = label), vjust = -0.5, position = position_dodge(width = 0.5), size = 6) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 20, color = "black"),
        axis.title.y = element_text(size = 20, color = "black"),
        axis.text.y = element_text(size = 20, color = "black"),
         panel.spacing = unit(1, "lines"))  +
  # Add the p-value as annotation
  annotate("text", x = 1.5, y = 135, label = paste("p =", format.pval(p_value, digits = 3)), size = 8)

ggsave(file.path(plot_path,"Figure_Sup_8A_Transcriptomic_ITH.pdf"),width= 6.5,height= 6.5)

#Save Figure data
All = All %>% select(sample, patient, treatment, ITH)
write.table( All, file.path(figures_data, "Figure_Sup_8A_Transcriptomic_ITH.txt"), sep = "\t", quote = F)
```

```{r }
sessionInfo()
```